# Generated by Django 5.1 on 2024-09-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colis', '0001_initial'),
        ('interface_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_utilisateur.utilisateur'),
        ),
    ]
