# Generated by Django 5.1 on 2024-09-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utilisateur', '0001_initial'),
        ('colis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_utilisateur.utilisateur'),
        ),
    ]
