# Generated by Django 5.1 on 2024-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('in_transit', 'En Transit'), ('delivered', 'Livré'), ('delayed', 'Retardé')], default='in_transit', max_length=20)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
