# Generated by Django 5.1 on 2024-09-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Livraison', '0001_initial'),
        ('colis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='colis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colis.colis'),
        ),
    ]
